services:
  postgres:
    build: .
    ports:
      - "5433:5432" 
    environment:
      POSTGRES_USER: 'guest' 
      POSTGRES_PASSWORD: 'password' 
      POSTGRES_DB: 'my-db' 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts
volumes:
  postgres_data: